### ISSUE TITLE
Long delay when inside of a deeply-nested git repository

### ISSUE THREAD

**Issue by bepzi** [ben01189998819991197253/contrail#17]
When inside of a folder deep within a git repository, `contrail` takes an unacceptably long time to display. I suspect this is due to having to recursively walk all the way back up the directory tree until it finds the git repository root, in which case, it might be prudent to only display the current git repository when at the repository root.

**Comment by Afulton11** [comment]
Could you just make a cache of git roots, compare the cache with the current working directory and if the current working directory contains the git root's directory path? Then we know we are inside a git repo and we know the exact location of the current git repo's root.

For example, the user goes to `~/GitRepo/deeply/nested/folder` or `~/GitRepo/` for the first time, we would save `~/GitRepo/` in a file somewhere, or in a `static` string array , then every time the user goes to a folder inside that git repo, we would simply compare the `cwd` with the path to all currently cached git roots and if a cached root's path matches the beginning of the current working directory, then we know we are in the git repo located at the matched git root.

This might cause us to have to compare the `cwd` with the cached git roots every time we `cd` , but it will probably be more efficient in the long run and we are already doing that with `git2` in `modules/git.rs`.

**Comment by bepzi** [comment]
I don't think that's feasible. What if the user does something like this:

```
mkdir new-get-repo && cd new-get-repo
git init
# Contrail thinks that they're in a git repository
cd ..
rm -rf new-get-repo
mkdir new-get-repo && cd new-get-repo
# Now we're in a regular folder, but contrail still thinks it's a git repo (names match)
```

Plus, I can't think of any reasonable way to maintain a cache. At what point does the cache get cleared? Set? No, I think the only reasonable way to do this is to only display when the user is at the repo root.

**Comment by bepzi** [comment]
`contrail` no longer recursively searches for git repositories. For my own convenience, I've added the following to my `~/.bashrc` (you can see the whole thing in my dotfiles repository):

```bash
alias groot='cd "$(git rev-parse --show-toplevel)"'
```

This command just takes you to the git repository root.
