### ISSUE TITLE
Ability to generate and output a fresh config file

### ISSUE THREAD

**Issue by bepzi** [ben01189998819991197253/contrail#6]
By passing a flag to contrail, perhaps named `generate_config`, we should be able to automatically generate a config file that the user can then modify.

We should then remove the `example_config.toml` file from the repo, as it will no longer be needed.

**Comment by Afulton11** [comment]
The `example_config.toml` could still be needed. We could just copy the contents of it into the generated config. This way we wouldn't have to hardcode the example config file in.

**Comment by Afulton11** [comment]
I have a pretty good generate_config function going, we can call `contrail -g -c file/path/here.toml` which will automatically generate the config file and place it on that path, creating any directories along the way, provided the file doesn't already exist. I'm thinking this type of functionality could be used put into the `ps1()` method in the `bash_profile`. Whenever we create the file, we would first ask the user to confirm that they put the correct path into `ps1()` so they don't accidentally create the incorrect directories.

**Comment by bepzi** [comment]
Solved by #15
